---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

tasks:
  run-server:
    cmds:
      - go run greeter_server/main.go

  run-client:
    cmds:
      - go run greeter_client/main.go

  run-client-http:
    cmds:
      - curl --location 'http://localhost:8081/v1/hello' --header 'Content-Type:application/json' --data '{"name":"Hello"}'

  generate:
    cmds:
      - go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
      - go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
      - go get google.golang.org/protobuf/cmd/protoc-gen-go
      - go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
      - go install google.golang.org/protobuf/cmd/protoc-gen-go
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - protoc  -I . --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative helloworld/helloworld.proto
      - protoc --grpc-gateway_out=. --grpc-gateway_opt paths=source_relative helloworld/helloworld.proto

